version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  init-dependencies:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  lint:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run lint
  check-formatting:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run format:check
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run tests
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - init-dependencies:
          filters:
            tags:
              only: /^v.*/
      - lint:
          requires:
            - init-dependencies
          filters:
            tags:
              only: /^v.*/
      - check-formatting:
          requires:
            - init-dependencies
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - lint
            - check-formatting
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
